### ISSUE TITLE
The volume of APK caused by lib is too large. Is there a specific way to solve it?

### ISSUE THREAD

**Issue by gpblg** [atsushieno/fluidsynth-midi-service-j#18]
The volume of APK caused by lib is too large. Is there a specific way to solve it?

**Comment by atsushieno** [comment]
quick solution ideas (not meant by either of them are doable without making changes to the sources):

- Use AAB instead of APK to not include irrelevant native shared libs.
- build single static libfluidsynth.so instead of bunch of glib dependencies.

**Comment by gpblg** [comment]
According to the phone processor type
Download the corresponding library from the network
Do you think it is feasible?

**Comment by atsushieno** [comment]
Take a look at how AAB works https://developer.android.com/platform/technology/app-bundle/

**Comment by gpblg** [comment]
> 看看AAB的工作原理https://developer.android.com/platform/technology/app-bundle/

Thank you! Benefited!
I ask you to have time to build a single file of the library.
Compiled environment is complex + my technical skills are weak, it can not be compiled successfully!

**Comment by atsushieno** [comment]
Check out issue #12 .
