### ISSUE TITLE
Class file not found: FluidsynthLibrary

### ISSUE THREAD

**Issue by gpblg** [atsushieno/fluidsynth-midi-service-j#19]
![image](https://user-images.githubusercontent.com/50068844/62998901-785dc700-be9f-11e9-90c7-588e47936bee.png)

![image](https://user-images.githubusercontent.com/50068844/62998924-8a3f6a00-be9f-11e9-9185-a24dc2cfb636.png)

![image](https://user-images.githubusercontent.com/50068844/62998979-a3481b00-be9f-11e9-8348-29e8312585a9.png)

**How can I get: FluidsynthLibrary**

**Comment by atsushieno** [comment]
Check out the build instruction. But note that it is quite complicated and you'll have to pass some paths at commandline to specify your local paths, listed on Makefile etc: https://github.com/atsushieno/fluidsynth-midi-service-j#building
