### ISSUE TITLE
Unresolved reference: FluidsynthLibrary

### ISSUE THREAD

**Issue by LeeTech** [atsushieno/fluidsynth-midi-service-j#21]
Unresolved reference: FluidsynthLibrary
![image](https://user-images.githubusercontent.com/18023710/110081648-3076fb80-7dc7-11eb-8940-ab38cdddeec0.png)

**Comment by atsushieno** [comment]
Follow this: https://github.com/atsushieno/fluidsynth-midi-service-j#building
