### ISSUE TITLE
build  error

### ISSUE THREAD

**Issue by yi1234** [atsushieno/fluidsynth-midi-service-j#24]
make prepare-fluidsynth and make
cd ../external/fluidsynth/doc/android && make -f Makefile.android prepare
make[1]: 进入目录“/home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android”
git clone https://github.com/Google/oboe.git /home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android/external/oboe 
正克隆到 '/home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android/external/oboe'...
remote: Enumerating objects: 14805, done.
remote: Counting objects: 100% (882/882), done.
remote: Compressing objects: 100% (455/455), done.
remote: Total 14805 (delta 420), reused 731 (delta 333), pack-reused 13923
接收对象中: 100% (14805/14805), 46.27 MiB | 4.20 MiB/s, 完成.
处理 delta 中: 100% (8928/8928), 完成.
cd /home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android/external/oboe
git clone https://github.com/atsushieno/cerbero.git /home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android/external/cerbero
正克隆到 '/home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android/external/cerbero'...
fatal: 无法访问 'https://github.com/atsushieno/cerbero.git/'：GnuTLS recv error (-54): Error in the pull function.
make[1]: *** [Makefile.android:49：/home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android/external/cerbero] 错误 128
make[1]: 离开目录“/home/zhongwen/AndroidProject/fluidsynth-midi-service-j/external/fluidsynth/doc/android”
make: *** [Makefile:14：prepare-fluidsynth] 错误 2

**Comment by atsushieno** [comment]
我看得懂中文一點點 but for future reference you should run commands with `LC_ALL=en(_US/_GB/*)` to get all the outputs in English, not everyone understands Chinese.

First try to google (well, baidu or whatever available locally) the error message to see if it is a known error message.

![image](https://user-images.githubusercontent.com/53929/121117017-6efed500-c852-11eb-8aad-fba001a5d705.png)

The top link navigates to https://www.programmersought.com/article/52661833918/ you can find your problem there.

But at Fluidsynth project ([Fluidsynth/fluidsynth](https://github.com/FluidSynth/fluidsynth)) we are in the process of switching to newer build scripts. Cerbero problems are hard to deal with. Fluidsynth Android binaries are built there everyday-ish. You can get the binaries and headers there, tweak the Makefiles in this repo and go forward. That would be probably even easier.

**Comment by yi1234** [comment]
thinks

**Comment by yi1234** [comment]
I don't understand Cerbero problems are hard to deal with. Fluidsynth Android binaries are built there everyday-ish. You can get the binaries and headers there, tweak the Makefiles in this repo and go forward. That would be probably even easier

**Comment by atsushieno** [comment]
Probably how this project achieves the goal is too difficult for you to deal with.

Chances are that I rewrite the `fluidsynthjna` build part to skip the entire Cerbero and related bits, but I cannot promise.

**Comment by yi1234** [comment]
Thanks for your help, I will still try to build my own project. The problem just now has been solved. Just modify the configuration file。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Atsushi ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 中午11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [atsushieno/fluidsynth-midi-service-j] build  error (#24)





 
可能这个项目如何实现目标对你来说太难了。
 
我可能会重写fluidsynthjna构建部分以跳过整个 Cerbero 和相关位，但我不能保证。
 
—
您收到此消息是因为您创作了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅。
